//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD5SumTest {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class test_resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal test_resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MD5SumTest.test_resources", typeof(test_resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ackermann_msgs/AckermannDrive 3512e91b48d69674a0e86fadf1ea8231
        ///ackermann_msgs/AckermannDriveStamped 1fd5d7f58889cefd44d29f6653240d0c
        ///actionlib_msgs/GoalID 302881f31927c1df708a2dbab0e80ee8
        ///actionlib_msgs/GoalStatusArray 8b2b82f13216d0a8ea88bd3af735e619
        ///actionlib_msgs/GoalStatus d388f9b87b3c471f784434d671988d4a
        ///actionlib/TestAction 991e87a72802262dfbe5d1b3cf6efc9a
        ///actionlib/TestActionFeedback 6d3d0bf7fb3dda24779c010a9f3eb7cb
        ///actionlib/TestActionGoal 348369c5b403676156094e8c159720bf
        ///actionlib/TestActio [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string msg_sums {
            get {
                return ResourceManager.GetString("msg_sums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die concert_msgs/AllocateSoftware 9a9d4cc73086cbcea67798fb6b0cda56
        ///concert_msgs/EnableService 1cec37e7e5df14d95c8bda48b6179b1a
        ///concert_msgs/UpdateServiceConfig c2c38c5e15ad95a99a740e6b43e333e5
        ///controller_manager_msgs/ListControllers 1341feb2e63fa791f855565d0da950d8
        ///controller_manager_msgs/ListControllerTypes c1d4cd11aefa9f97ba4aeb5b33987f4e
        ///controller_manager_msgs/LoadController 647e5c54b8d6468952d8d31f1efe96c0
        ///controller_manager_msgs/ReloadControllerLibraries 40e8c411fd1797d2e2c486018f846040
        ///controller_ [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string srv_sums {
            get {
                return ResourceManager.GetString("srv_sums", resourceCulture);
            }
        }
    }
}
